apiVersion: v2
name: slskd
description: slskd Soulseek daemon (no VPN for now)
type: application
version: 1.0.1
appVersion: 0.26.0
dependencies:
- name: app-template
  version: 5.2.1
  repository: https://bjw-s-labs.github.io/helm-charts/
