apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: betanin
spec:
  refreshInterval: 1h
  target:
    name: betanin
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        BETANIN_API_KEY: "{{ `{{ .api_key }}` }}"
        config.toml: |
          [frontend]
          username = "{{ `{{ .username }}` }}"
          password = "{{ `{{ .password }}` }}"

          [clients]
          api_key = "{{ `{{ .api_key }}` }}"

          [server]
          num_parallel_jobs = 1

          [notifications.services]

          [notifications.strings]
          body  = "@ $time. view/use the console at http://127.0.0.1:9393/$console_path"
          title = "[betanin] torrent `$name` $status"
        beets-config.yaml: |
          directory: /media/Music/automation
          library: /b/.config/beets-db/library.db

          import:
            move: no
            copy: no
            write: yes
            quiet: yes
            quiet_fallback: skip
            timid: no
            resume: no

          plugins: chroma fetchart embedart lastgenre replaygain

          chroma:
            auto: yes
          acoustid:
            apikey: {{ `{{ .acoustid_key }}` }}
          fetchart:
            sources: coverart itunes amazon albumart
          embedart:
            auto: yes
          lastgenre:
            auto: yes
            source: album
          lastfm:
            api_key: {{ `{{ .lastfm_key }}` }}
          replaygain:
            backend: ffmpeg
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "betanin" }}'
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "betanin" }}'
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: api_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "betanin" }}'
        property: api_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: acoustid_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "betanin" }}'
        property: acoustid_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: lastfm_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "betanin" }}'
        property: lastfm_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
