---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-mediamanager
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5-19-bookworm
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: local-path
  monitoring:
    enablePodMonitor: true
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
  bootstrap:
    initdb:
      database: mediamanager
      owner: mediamanager
      secret:
        name: pg-mediamanager-secret
