apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-mcp
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: SecretStore
  target:
    name: argocd-mcp
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: token
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "argocd-mcp" }}'
        property: password
        # Boiler plate needed for ArgoCD to not complain about a mismatch.
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
