apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-open-webui-mcp-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: SecretStore
  target:
    name: pg-open-webui-mcp-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: readonly
        password: '{{ `{{ .password }}` }}'
  data:
    - secretKey: password
      remoteRef:
        key: {{ index .Values "bitwardenIds" "mcp-pg-open-webui" }}
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
