apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-shared
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1000Gi
  csi:
    driver: seaweedfs-csi-driver
    volumeHandle: dev-shared
    volumeAttributes:
      collection: dev
      replication: "002"
      path: /buckets/dev
      #diskType: "ssd"
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-shared
spec:
  storageClassName: ""
  volumeName: dev-shared
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
