apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homeassistant-mcp
  namespace: default
spec:
  refreshInterval: 1h
  target:
    name: homeassistant-mcp
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HA_TOKEN: "{{ `{{ .token }}` }}"
        HA_URL: "{{ `{{ .url }}` }}"
  data:
    - secretKey: token
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "homeassistant-mcp" }}'
        property: password
        # Boiler plate needed for ArgoCD to not complain about a mismatch.
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: url
      sourceRef:
        storeRef:
          name: bitwarden-uri
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "homeassistant-mcp" }}'
        # Boiler plate needed for ArgoCD to not complain about a mismatch.
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

