apiVersion: v2
name: base
version: 1.0.191
appVersion: 1.0.31
dependencies:
- name: argo-cd
  version: 10.1.4
  repository: https://argoproj.github.io/argo-helm
- name: cert-manager
  version: v1.21.1
  repository: https://charts.jetstack.io
