apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "actualbudget-sso-secret"
spec:
  refreshInterval: 1h
  target:
    name: "actualbudget-sso-secret"
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACTUAL_OPENID_DISCOVERY_URL: "{{ `{{ .discovery_url }}` }}"
        ACTUAL_OPENID_CLIENT_ID: "{{ `{{ .client_id }}` }}"
        ACTUAL_OPENID_CLIENT_SECRET: "{{ `{{ .client_secret }}` }}"
        ACTUAL_OPENID_SERVER_HOSTNAME: "https://{{ .Release.Name }}.{{ .Values.domain }}"
        ACTUAL_OPENID_ENFORCE: "true"
        ACTUAL_USER_CREATION_MODE: "login"
  data:
    - secretKey: client_id
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "actualbudget-sso-secret" }}'
        property: username
        # Boiler plate needed for ArgoCD to not complain about a mismatch.
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: client_secret
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "actualbudget-sso-secret" }}'
        property: password
        # Boiler plate needed for ArgoCD to not complain about a mismatch.
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: discovery_url
      sourceRef:
        storeRef:
          name: bitwarden-uri
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "actualbudget-sso-secret" }}'
        # Boiler plate needed for ArgoCD to not complain about a mismatch.
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
